spring:
   application:
      name: twitter-filter-service
   server:
port: 8080

twitter:
   consumerKey: EG8GNL0nP2LWW38FqDZN8UBJo 
   consumerSecret: P0lBGq1POMXXvWEn5IBgO3FimdTRtr9ywYgvVm0AIwcJrhIK2U