server:
   port:    8080

spring:
   application:
      name: twitter-filter-service
   datasource: 
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:twitter-db;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: create-drop 
      properties:
         hibernate:
            format_sql: true
      show-sql: true
   

twitter:
   consumerKey: EG8GNL0nP2LWW38FqDZN8UBJo 
   consumerSecret: P0lBGq1POMXXvWEn5IBgO3FimdTRtr9ywYgvVm0AIwcJrhIK2U
   default-hashtags: openbanking, apifirst, devops, cloudfirst, microservices, apigateway, oauth, swagger, raml, openapis
   
