port: 8080

spring:
   application:
      name: twitter-filter-service
   datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
   jpa:
      properties: 
         hibernate: 
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: update 
   

twitter:
   consumerKey: EG8GNL0nP2LWW38FqDZN8UBJo 
   consumerSecret: P0lBGq1POMXXvWEn5IBgO3FimdTRtr9ywYgvVm0AIwcJrhIK2U
   default-hashtags: openbanking, apifirst, devops, cloudfirst, microservices, apigateway, oauth, swagger, raml, openapis
   
