server:
   port: ${PORT:8080}

spring:
   application:
      name: twitter-filter-service
   datasource:
      driverClassName: org.postgresql.Driver
      url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
   jpa:
      properties: 
         hibernate: 
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: none 

twitter:
   consumerKey: ${TWITTER_CONSUMER_KEY} 
   consumerSecret: ${TWITTER_CONSUMER_SECRET}
   
